---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hoge
  description: hogehoge
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: lapi
  lifecycle: production
  providesApis:
  - aaa-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: aaa-api
  description: piyo
spec:
  type: openapi
  lifecycle: production
  owner: lapi
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
